using PathOfTerraria.Common.Mechanics;
using PathOfTerraria.Common.Systems.PassiveTreeSystem;
using PathOfTerraria.Common.Systems.Skills;
using PathOfTerraria.Common.UI.Guide;
using PathOfTerraria.Common.UI.Hotbar;
using PathOfTerraria.Content.Passives.Magic.Masteries;
using System.Collections.Generic;
using System.Linq;
using Terraria.GameInput;
using Terraria.Localization;
using Terraria.ModLoader.Core;
using Terraria.ModLoader.IO;

namespace PathOfTerraria.Common.Systems.ModPlayers.SkillPlayers;

internal class SkillCombatPlayer : ModPlayer
{
	public static ModKeybind Skill1Keybind;
	public static ModKeybind Skill2Keybind;
	public static ModKeybind Skill3Keybind;

	public readonly Skill[] HotbarSkills = new Skill[3];
	public Skill[] UnlockedSkills = [];
	
	public int Points;
	public SkillBuff GlobalBuff = new();
	public int TicksSinceSkillLastUsed = 0;

	public override void Load()
	{
		if (Main.dedServ)
		{
			return;
		}

		Skill1Keybind = KeybindLoader.RegisterKeybind(Mod, "UseSkill1", "3");
		Skill2Keybind = KeybindLoader.RegisterKeybind(Mod, "UseSkill2", "4");
		Skill3Keybind = KeybindLoader.RegisterKeybind(Mod, "UseSkill3", "5");

#if DEBUG
		// This code only runs in debug as we don't need to do this in production; keys would already be generated by this point.
		// This code autogenerates the keys for both the name and description of a skill.

		IEnumerable<Type> skills = AssemblyManager.GetLoadableTypes(Mod.Code).Where(x => typeof(Skill).IsAssignableFrom(x) && !x.IsAbstract);

		foreach (Type skillType in skills)
		{
			var skill = Skill.GetAndPrepareSkill(skillType);

			Language.GetOrRegister("Mods.PathOfTerraria.Skills." + skill.Name + ".Name", () => "");
			Language.GetOrRegister("Mods.PathOfTerraria.Skills." + skill.Name + ".Description", () => "");
		}
#endif
	}

	public override void SetControls()
	{
		if (!NewHotbar.LocalCombatMode)
		{
			return;
		}

		for (int i = 1; i < 11; ++i)
		{
			CheckHotbarOverlap("Hotbar" + i);
		}
	}

	/// <summary>
	/// "Unsets" a hotbar hotkey if it overlaps with a skill keybind, so you can use a skill and not switch items.
	/// </summary>
	/// <param name="hotbarKey"></param>
	private static void CheckHotbarOverlap(string hotbarKey)
	{
		if (PlayerInput.Triggers.Current.KeyStatus[hotbarKey] && SkillMatchesVanillaKeyBind(hotbarKey))
		{
			PlayerInput.Triggers.Current.KeyStatus[hotbarKey] = false;
		}
	}

	private static bool SkillMatchesVanillaKeyBind(string key)
	{
		if (PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus[key].Count == 0)
		{
			return false;
		}

		foreach (string hotkey in PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus[key])
		{
			if (Skill1Keybind.GetAssignedKeys().Contains(hotkey))
			{
				return true;
			}

			if (Skill2Keybind.GetAssignedKeys().Contains(hotkey))
			{
				return true;
			}

			if (Skill3Keybind.GetAssignedKeys().Contains(hotkey))
			{
				return true;
			}
		}

		return false;
	}

	public override void ProcessTriggers(TriggersSet triggersSet)
	{
		if (Main.myPlayer != Player.whoAmI || Player.dead || !NewHotbar.LocalCombatMode)
		{
			return;
		}

		if (Skill1Keybind.JustPressed)
		{
			UseSkill(0);
		}

		if (Skill2Keybind.JustPressed)
		{
			UseSkill(1);
		}

		if (Skill3Keybind.JustPressed)
		{
			UseSkill(2);
		}
	}

	public void UseSkill(int index)
	{
		SkillFailure _ = default;

		if (HotbarSkills[index] != null && HotbarSkills[index].CanUseSkill(Player, ref _, false))
		{
			Player.GetModPlayer<TutorialPlayer>().TutorialChecks.Add(TutorialCheck.UsedASkill);

			HotbarSkills[index].RecalculateStats(Player);
			HotbarSkills[index]?.UseSkill(Player);

			if (Player.GetModPlayer<PassiveTreePlayer>().TryGetCumulativeValue<AnticipatedStrikeMastery>(out float value) && TicksSinceSkillLastUsed > value * 60)
			{
				// Offset mouse so the usage doesn't perfectly overlap every time
				Vector2 mouse = new(Main.mouseX, Main.mouseY);
				float radius = Main.rand.NextFloat(30, 60);
				Vector2 offset = Main.rand.NextVector2CircularEdge(radius, radius);

				Main.mouseX += (int)offset.X;
				Main.mouseY += (int)offset.Y;

				HotbarSkills[index]?.UseSkill(Player);

				Main.mouseX = (int)mouse.X;
				Main.mouseY = (int)mouse.Y;
			}

			foreach (ModPlayer player in Player.ModPlayers)
			{
				if (player is SkillHooks.IOnUseSkillPlayer use)
				{
					use.OnUseSkill(HotbarSkills[index]);
				}
			}

			TicksSinceSkillLastUsed = 0;
		}
	}

	public override void ResetEffects()
	{
		TicksSinceSkillLastUsed++;
		GlobalBuff.Reset();

		if (HotbarSkills == null || HotbarSkills.Length == 0)
		{
			return;
		}

		foreach (Skill skill in HotbarSkills)
		{
			if (skill is { Cooldown: > 0 })
			{
				skill.Cooldown--;
			}
		}
	}

	public override void SaveData(TagCompound tag)
	{
		for (int i = 0; i < HotbarSkills.Length; i++)
		{
			Skill skill = HotbarSkills[i];

			if (skill is null)
			{
				return;
			}

			TagCompound skillTag = new()
			{
				{ "type", skill.GetType().AssemblyQualifiedName }
			};

			skill.SaveData(skillTag);
			tag.Add("skill" + i, skillTag);
		}
		
		tag["points"] = Points;
	}

	public override void LoadData(TagCompound tag)
	{
		for (int i = 0; i < HotbarSkills.Length; ++i)
		{
			if (!tag.ContainsKey("skill" + i))
			{
				return;
			}

			TagCompound data = tag.GetCompound("skill" + i);
			string type = data.GetString("type");

			var skill = Skill.GetAndPrepareSkill(Type.GetType(type));
			skill.LevelTo(skill.Level);
			skill.LoadData(data, Player);

			HotbarSkills[i] = skill;
		}
	}

	public bool TryGetSkill<T>(out Skill skill) where T : Skill
	{
		skill = null;

		for (int i = 0; i < HotbarSkills.Length; i++)
		{
			if (HotbarSkills[i] is not null && HotbarSkills[i].GetType() == typeof(T))
			{
				skill = HotbarSkills[i];
				return true;
			}
		}

		return false;
	}

	public bool HasSkill(string name)
	{
		for (int i = 0; i < HotbarSkills.Length; i++)
		{
			if (HotbarSkills[i] is not null && HotbarSkills[i].Name == name)
			{
				return true;
			}
		}

		return false;
	}

	/// <summary> Tries to add the given skill to the player. </summary>
	/// <param name="suppress"> Whether to display Main.NewText feedback. </param>
	/// <param name="slot"> The slot to add to directly. Used only by <see cref="UI.SkillSelect.SkillSelectUI"/>. </param>
	public bool TryAddSkill(Skill skill, bool suppress = false, int slot = -1)
	{
		SkillFailure fail = default;

		if (!skill.CanEquipSkill(Player, ref fail))
		{
			NewText($"{Language.GetTextValue("Mods.PathOfTerraria.Skills.CantBeAdded")} ({fail.Description.Value})");
			return false; // Couldn't equip skill, return false
		}

		for (int i = 0; i < HotbarSkills.Length; ++i)
		{
			if (HotbarSkills[i] != null && HotbarSkills[i].Name == skill.Name)
			{
				NewText(Language.GetTextValue("Mods.PathOfTerraria.Skills.AlreadyAdded"));

				// When slot is -1, return true to allow the skill tree to be opened
				// Otherwise, return false since it was not successfully equipped
				return slot == -1;
			}
		}

		if (slot == -1)
		{
			for (int i = 0; i < HotbarSkills.Length; i++)
			{
				if (HotbarSkills[i] == null)
				{
					HotbarSkills[i] = skill;
					HotbarSkills[i].LevelTo(HotbarSkills[i].Level);

					return true; // Equipped skill, return true
				}
			}
		}
		else
		{
			HotbarSkills[slot] = skill;
			HotbarSkills[slot].LevelTo(HotbarSkills[slot].Level);

			return true; // Equipped skill, return true
		}

		return false; // No space, fail

		void NewText(string value)
		{
			if (!suppress)
			{
				Main.NewText(value);
			}
		}
	}

	public bool TryRemoveSkill(Skill skill)
	{
		for (int i = 0; i < HotbarSkills.Length; i++)
		{
			if (HotbarSkills[i] != null && HotbarSkills[i].GetType() == skill.GetType())
			{
				HotbarSkills[i] = null;
				return true;
			}
		}

		return false;
	}
}