name: .NET Lint

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Pull TML
      run: |
        cd ..
        mkdir ./tmod
        touch tModLoader.targets
        
        echo '<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <Import Project=".\tmod\tMLMod.targets" />
        </Project>' > tModLoader.targets
        
        cd ./tmod
        wget https://github.com/tModLoader/tModLoader/releases/latest/download/tModLoader.zip
        unzip tModLoader.zip
        cd ..
        cd ./PathOfTerraria
        
      
    - name: Lint
      run: dotnet format style PathOfTerraria.sln --verify-no-changes